apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-website
  namespace: paymentops-site
  labels:
    app: paymentops-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentops-website
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: paymentops-website
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ghcr-pull
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: paymentops-website
          image: ghcr.io/cloodnova/paymentops-website:22548e3bf555964cf0f423ed6470a846d2a2e1f7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_SITE_URL
              value: https://paymentops-hetzner.cloudnova.tech
            - name: NEXT_PUBLIC_APP_URL
              value: https://paymentops-app.cloudnova.tech
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: next-cache
              mountPath: /app/.next/cache
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 20m
              memory: 48Mi
            limits:
              cpu: 150m
              memory: 192Mi
      volumes:
        - name: next-cache
          emptyDir: {}
