apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - httproute.yaml

images:
  - name: ghcr.io/sanketnawale/cloudnova-v2
    newTag: sha-7ebca26

patches:
  - path: patch-deployment.yaml
