apiVersion: v1
kind: Service
metadata:
  name: mira-metabase
  namespace: mira-metabase
spec:
  type: ClusterIP
  selector:
    app: mira-metabase
  ports:
    - name: http
      port: 80
      targetPort: 3000