apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-postgres-data
  namespace: mira-metabase
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi