apiVersion: v1
kind: Service
metadata:
  name: paymentops-postgres
  namespace: paymentops
spec:
  type: ClusterIP
  selector:
    app: paymentops-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
