apiVersion: v1
kind: Namespace
metadata:
  name: gateway-infra
  labels:
    app.kubernetes.io/name: gateway-infra
    app.kubernetes.io/part-of: loudnova-platform
    app.kubernetes.io/managed-by: kustomize