apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-website
  namespace: paymentops-site
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: paymentops-website
          image: ghcr.io/cloodnova/paymentops-website:aa86ea85eea15119dbcae10268e0b965c6456d1d
