apiVersion: v1
kind: Service
metadata:
  name: cloudnova-agent-office
  namespace: cloudnova-agents
  labels:
    app: cloudnova-agent-office
spec:
  type: ClusterIP
  selector:
    app: cloudnova-agent-office
  ports:
    - name: http
      port: 4520
      targetPort: http
