apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudnova-web.yaml
  - cloudflare-tunnel.yaml
  - envoy-gateway-install.yaml
  - envoy-gateway-runtime.yaml
  - gotk-components.yaml
  - gotk-sync.yaml
  - failover-controller.yaml
