apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-address-structuring
  namespace: paymentops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: address-structuring
          image: ghcr.io/cloodnova/paymentops-address-structuring:0ded7aacb7ff6036279629635b6f386867ff0af9
