apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-worker
  namespace: paymentops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: paymentops-worker
          image: ghcr.io/cloodnova/paymentops-worker:7e835cdeb25f77ae98ddc98098a58a53f29143d6

