apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-api
  namespace: paymentops
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: paymentops-api
          image: ghcr.io/cloodnova/paymentops-api:b9700c858406e771daec0f70d3afbda709c94051

