apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-api
  namespace: paymentops
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: paymentops-api
          image: ghcr.io/cloodnova/paymentops-api:d9a30d0dba9685d6cbe70c771f3df65a57ff5b35

