apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-address-structuring
  namespace: paymentops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: address-structuring
          image: ghcr.io/cloodnova/paymentops-address-structuring:de7e3d2fca25382c20b96004b7059497281af955
