apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-worker
  namespace: paymentops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: paymentops-worker
          image: ghcr.io/cloodnova/paymentops-worker:061559f2ec097509e1f9f6a7bca345800847e085

