apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-web
  namespace: paymentops
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: paymentops-web
          image: ghcr.io/cloodnova/paymentops-web:755e23923ceaff7895073781551d939c578a36ec

