apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-api
  namespace: paymentops
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: paymentops-api
          image: ghcr.io/cloodnova/paymentops-api:7922177f1a97b12f54d0a99ba449736c3fd96234

