apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-worker
  namespace: paymentops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: paymentops-worker
          image: ghcr.io/cloodnova/paymentops-worker:883a978c582df315e870f5ec3f948a2320aa3c26

