apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentops-web
  namespace: paymentops
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: paymentops-web
          image: ghcr.io/cloodnova/paymentops-web:c4e7252161243c2a1087f219a5769241b87b6e9e

