apiVersion: apps/v1
kind: Deployment
metadata:
  name: mira-web
  namespace: mira-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mira-web
  template:
    metadata:
      labels:
        app: mira-web
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: mira-web
          image: ghcr.io/sanketnawale/mira:sha-1dd924b
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30