apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnova-web
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/loudnova/apps/cloudnova-web/overlays/test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system