apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- cloudnova-dashboard.yaml
- cloudnova-web.yaml
- flux-web.yaml
- netdata.yaml

patches:
  - target:
      kind: Namespace
      name: flux-system
    patch: |-
      - op: add
        path: /metadata/labels/loudnova.cloudnova.tech~1public-routes
        value: "true"

